# See documentation: https://www.gitpod.io/docs/config-gitpod-file

---
# Commands to start on workspace startup
tasks:
  - init: |
      # Install mob tool.
      curl -sL install.mob.sh | sh -s - --user
      alias mob=/home/gitpod/.local/bin/mob

vscode:
  extensions:
    - mhutchie.git-graph